CREATING THE CAKE
Take three large eggs, beat them, and seperate the whites and yolks
 Mix them well, and sprinkle small amounts of vanilla Syrup and white Sugar
Now add fair amounts of white and dark Chocolate, and mix them with a hand and electronic mixer
Add Icing Sugar, Baking Powder, Flour and Butter, and then mix again
Freeze the cake in a round or square moulding bowl.
Freeze for atleast 1hr
After freezing, take the cake out, and put Whipped Cream on the sides, Chocolate Frosting on the sides of the top
Add icing sugar on the top with Choco Chips
Now savour this cake on Christmas Eve